<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\common.props"/>

    <PropertyGroup>
        <!-- Root Namespace -->
        <RootNamespace>PPWCode.Server.Core</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
    </ItemGroup>

    <ItemGroup>
        <!-- PPWCode -->
        <PackageReference Include="PPWCode.Vernacular.NHibernate.III"/>
        <PackageReference Include="PPWCode.API.Core"/>

        <!-- NHibernate -->
        <PackageReference Include="NHibernateProfiler.Appender"/>

        <!-- System -->
        <PackageReference Include="System.Configuration.ConfigurationManager"/>
        <PackageReference Include="Asp.Versioning.Mvc"/>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Managers\Implementations\DropAll.sql"/>
    </ItemGroup>

</Project>
