<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- target frameworks -->
    <TargetFrameworks>net6.0;net8.0</TargetFrameworks>

    <!-- Root Namespace -->
    <RootNamespace>PPWCode.Server.Core</RootNamespace>

    <!-- nuget package -->
    <IsPackable>true</IsPackable>

    <!-- Stylecop -->
    <CodeAnalysisRuleSet>..\StyleCop.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <!-- PPWCode -->
    <PackageReference Include="PPWCode.Vernacular.NHibernate.III" Version="3.0.0-rc010076" />
    <PackageReference Include="PPWCode.API.Core" Version="1.3.0-rc010038" />

    <!-- Castle Windsor -->
    <PackageReference Include="Castle.Windsor" Version="5.1.1" />
    
    <!-- NHibernate -->
    <PackageReference Include="NHibernateProfiler.Appender" Version="6.0.6047" />

    <!-- System -->
    <PackageReference Include="System.Data.SqlClient" Version="4.8.6" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="5.1.0" />
  </ItemGroup>

  <Choose>
    <When Condition=" '$(TargetFramework)' == 'net6.0' ">
      <ItemGroup>
        <PackageReference Include="System.Configuration.ConfigurationManager" Version="6.0.*" />
      </ItemGroup>
    </When>
    <When Condition=" '$(TargetFramework)' == 'net8.0' ">
      <ItemGroup>
        <PackageReference Include="System.Configuration.ConfigurationManager" Version="8.0.*" />
      </ItemGroup>
    </When>
  </Choose>
  
  <ItemGroup>
    <EmbeddedResource Include="Managers\Implementations\DropAll.sql" />
  </ItemGroup>

</Project>
